## compress_csv_to_gzip ,compress_json_to_gzip ,aggregation ,anonymization ,filtering
stages:
  - name: stage_1
    type: filtering
    parameter:
      p1: something
      p2:
        key: value
        key2: value2
  - name: stage_2
    type: aggregation
    parameter:
      p1: something
      p2: someother thing

pipelines:
  - name: p_1
    flow:
      - stage_1
      - stage_2
    datasource:
      type: file
      metadata : path/to/your/dataset

  - name: p_2
    flow:
      - stage 1
      - stage 2
    datasource:
      type: pipeline
      metadata : p1

