apiVersion: apps/v1
kind: Deployment
metadata:
  name: csv-reader
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csv-reader
  template:
    metadata:
      labels:
        app: csv-reader
    spec:
      containers:
      - name: csv-reader
        image: sepidmas/csv-reader:latest  # Make sure this image exists locally
        ports:
        - containerPort: 5000

